name: Publish a developer package

on:
  push:
    branches:
      - main

permissions:
  packages: write
  contents: read

jobs:
  publish:
    uses: ./.github/workflows/publish-package.yml

    with:
      npm-registry-url: 'https://npm.pkg.github.com'

    secrets:
      npm-token: ${{ secrets.GITHUB_TOKEN }}
